module.exports = {
  GET_LOGIN_STATUS: 'GET_LOGIN_STATUS',
  INITIALIZE_GAME: 'INITIALIZE_GAME',
  LEVEL_UP: 'LEVEL_UP',
  PAUSE: 'PAUSE',
  GET_NEXT_SHAPE: 'GET_NEXT_SHAPE',
  SCREEN_UPDATE: 'SCREEN_UPDATE',
  RAISE_FLOOR: 'RAISE_FLOOR',
  COLLISION: 'COLLISION',
};
